rajddesai/ngx-admin

- src/app/pages/maps/search-map/entity/Location.ts
- src/polyfills.ts
> Updating fork

- src/app/ext/dealflowpage/dealflowpage.html
- src/app/pages/dealflowpage/dealflowpage.component.ts
- src/app/pages/dealflowpage/dealflowpage.html
>  added scheduling tab for dealflow

- src/app/pages/dealflowpage/dealflowpage.component.ts
- src/app/pages/dealflowpage/dealflowpage.html
- src/app/pages/dealflowpage/dealflowpage.module.ts
> dealflowpage schedule update

- src/app/@theme/styles/global.scss
- src/app/@theme/styles/themes.scss
- src/app/pages/corporations/corporations.html
- src/app/pages/dealflowform/attendee.component.html
- src/app/pages/dealflowform/attendee.component.ts
- src/app/pages/dealflowform/dealflowform-routing-module.ts
- src/app/pages/dealflowform/dealflowform.component.ts
- src/app/pages/dealflowform/dealflowform.html
- src/app/pages/dealflowform/dealflowform.interface.ts
- src/app/pages/dealflowform/dealflowform.module.ts
- src/app/pages/dealflowform/dealflowform.scss
- src/app/pages/dealflowform/dealflowform.service.ts
- src/app/pages/dealflowform/index.ts
- src/app/pages/dealflowform/supportingMember.component.html
- src/app/pages/dealflowform/supportingMember.component.ts
- src/app/pages/dealflowlists/dealflowlists.html
- src/app/pages/dealflowpage/dealflowpage.html
- src/app/pages/dealflowpage/dealflowpage.scss
- src/app/pages/pages-routing.module.ts
- src/app/pages/portfolio/portfolio.html
- src/app/pages/startups/startups.html
> Albert's changes

- src/app/pages/dealflowpage/dealflowpage.html
>  added checkbox to dealflowpage schedule

- src/app/pages/dealflowpage/dealflowpage.component.ts
- src/app/pages/dealflowpage/dealflowpage.html
> WIP scheduling dealflow

- src/app/pages/dealflowform/supportingMember.component.ts
- src/app/pages/dealflowpage/dealflowpage.component.ts
- src/app/pages/dealflowpage/dealflowpage.html
> dealflowform minor fix

- src/app/ext/dealflowpage/dealflowpage.html
- src/app/ext/dealflowpage/dealflowpage.scss
> Ron's mistakes fixed

- src/app/ext/dealflowpage/dealflowpage.html
> Ext Page margin fixes

- src/app/ext/dealflowpage/dealflowpage.html
- src/app/ext/dealflowpage/dealflowpage.scss
- src/app/pages/dealflowpage/dealflowpage.html
- src/app/pages/startups/startups.component.ts
- src/app/pages/startups/startups.html
> Edited ext Dealflow Page and Dealflow Page

- src/app/ext/dealflowpage/dealflowpage.component.ts
- src/app/ext/dealflowpage/dealflowpage.html
>  ext dealflowpage changes

- src/app/ext/dealflowpage/dealflowpage.html
- src/app/pages/dealflowpage/dealflowpage.html
> Ext Dealflow Page Change

- src/app/ext/dealflowpage/dealflowpage.html
- src/app/ext/dealflowpage/dealflowpage.scss
> Small CSS change

- src/app/ext/dealflowpage/dealflowpage.component.ts
- src/app/pages/dealflowpage/dealflowpage.component.ts
- src/app/pages/dealflowpage/dealflowpage.html
- src/app/pages/dealflowpage/dealflowpage.service.ts
> dealflowpage debug changes

- src/app/ext/dealflowpage/dealflowpage.component.ts
- src/app/pages/dealflowlists/dealflowlists.component.ts
- src/app/pages/dealflowlists/dealflowlists.html
- src/app/pages/dealflowpage/dealflowpage.component.ts
- src/app/pages/dealflowpage/dealflowpage.html
- src/app/pages/dealflowpage/dealflowpage.module.ts
- src/app/pages/startups/startups.component.ts
>  dealflowlist state bug fix and added mat-select

- src/app/pages/dealflowpage/dealflowpage.html
- src/app/pages/editdealflow/editdealflow.component.ts
- src/app/pages/editdealflow/editdealflow.html
> Edits to Scheduling Tab

- src/app/ext/dealflowpage/dealflowpage.component.ts
- src/app/ext/dealflowpage/dealflowpage.html
- src/app/pages/dealflowlists/dealflowlists.html
- src/app/pages/dealflowpage/dealflowpage.component.ts
- src/app/pages/dealflowpage/dealflowpage.html
> Dealflow Page and List Edits

- src/app/pages/dealflowform/agenda.component.ts
- src/app/pages/dealflowform/agenda.html
- src/app/pages/dealflowform/dealflowform.component.ts
- src/app/pages/dealflowform/dealflowform.html
- src/app/pages/dealflowform/dealflowform.interface.ts
- src/app/pages/dealflowform/dealflowform.module.ts
- src/app/pages/dealflowpage/dealflowpage.component.ts
- src/app/pages/dealflowpage/dealflowpage.html
- src/app/pages/editdealflow/editdealflow.component.ts
>  fixed corporate autofill and changed format for event_agenda

- src/app/pages/dealflowform/dealflowform.component.ts
- src/app/pages/dealflowform/dealflowform.html
- src/app/pages/editdealflow/agenda.component.ts
- src/app/pages/editdealflow/agenda.html
- src/app/pages/editdealflow/editdealflow.component.ts
- src/app/pages/editdealflow/editdealflow.html
- src/app/pages/editdealflow/editdealflow.interface.ts
- src/app/pages/editdealflow/editdealflow.module.ts
>  added new event_agenda to editdealflow with auto populate

- src/app/pages/dealflowform/dealflowform.component.ts
- src/app/pages/dealflowform/dealflowform.html
- src/app/pages/dealflowpage/dealflowpage.html
- src/app/pages/editdealflow/attendee.component.html
- src/app/pages/editdealflow/supportingMember.component.html
> Lots of fixes

- src/app/pages/dealflowpage/dealflowpage.component.ts
- src/app/pages/dealflowpage/dealflowpage.html
- src/app/pages/dealflowpage/dealflowpage.scss
- src/app/pages/dealflowpage/dealflowpage.service.ts
> added priority selection to dealflowpage

- src/app/@theme/styles/themes.scss
- src/app/app-routing.module.ts
- src/app/ext/confirmdealflow/confirmdealflow-routing-module.ts
- src/app/ext/confirmdealflow/confirmdealflow.component.ts
- src/app/ext/confirmdealflow/confirmdealflow.html
- src/app/ext/confirmdealflow/confirmdealflow.module.ts
- src/app/ext/confirmdealflow/confirmdealflow.scss
- src/app/ext/confirmdealflow/confirmdealflow.service.ts
- src/app/ext/dealflowpage/dealflowpage.html
- src/app/pages/dealflowpage/dealflowpage.html
- src/app/pages/dealflowpage/dealflowpage.scss
> Added Confirm Dealflow Page

- src/app/pages/dealflowpage/dealflowpage.component.ts
- src/app/pages/dealflowpage/dealflowpage.html
> minor dealflowpage changes + scheduling WIP

- src/app/ext/feedback/feedback.html
> Feedback Page Update
